name: Claude Code • auto-label issues

on:
  issues:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    name: Auto-label issues for Claude processing
    permissions:
      issues: write
    steps:
      # Checkout repo (required if you later read files)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install GitHub CLI and Claude CLI
      - name: Install GitHub & Claude CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          npm install -g @anthropic-ai/claude-code
    
      - name: Classify issue via Claude API
        env:
            ANTHROPIC_API_KEY: ${{ secrets.ANTHOPIC_API_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            ISSUE_TITLE="${{ github.event.issue.title }}"
            ISSUE_BODY="${{ github.event.issue.body }}"

            PROMPT="Classify this GitHub issue into one of: broken_links, spelling_mistakes, grammatical_errors, formatting_issues, suggestions.
            Title: $ISSUE_TITLE
            Body: $ISSUE_BODY
            Respond ONLY with the category name."

            RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
            -H "Content-Type: application/json" \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -d "{   
                \"model\": \"claude-3-5-sonnet-20240620\",S
                \"max_tokens\": 50,
                \"messages\": [{\"role\": \"user\", \"content\": \"$PROMPT\"}]
            }")
            echo "Response: $RESPONSE"

            CATEGORY=$(echo "$RESPONSE" | jq -r '.content[0].text' | tr -d 'S\n')
            echo "Category: $CATEGORY"

            # Add label if classification returned a category
            if [[ -n "$CATEGORY" && "$CATEGORY" != "null" ]]; then
            gh issue edit ${{ github.event.issue.number }} --add-label "claude:queue"
            fi

