name: Claude Code • auto-label issues

on:
  issues:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    name: Auto-label issues for Claude processing
    permissions:
      issues: write
    steps:
      # Checkout repo (required if you later read files)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          sudo apt-get install -y jq curl
    
      - name: Analyze issue with Claude
        id: claude
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"

          PROMPT="Classify the following GitHub issue. If it is about broken links, spelling mistakes, grammatical errors, documentation formatting issues, or general suggestions, respond ONLY with 'YES'. Otherwise respond ONLY with 'NO'.

          Title: $ISSUE_TITLE
          Body: $ISSUE_BODY"

          RESPONSE=$(curl https://api.anthropic.com/v1/messages \
            -H "Content-Type: application/json" \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -d "{
              \"model\": \"claude-3-opus-20240229\",
              \"max_tokens\": 20,
              \"messages\": [{\"role\": \"user\", \"content\": \"$PROMPT\"}]
            }")

          ANSWER=$(echo "$RESPONSE" | jq -r '.content[0].text' | tr '[:upper:]' '[:lower:]')

          echo "Claude Answer: $ANSWER"

          if [[ "$ANSWER" == "yes" ]]; then
            echo "Adding claude:queue label"
            gh issue edit "$ISSUE_NUMBER" --add-label "claude:queue"
          else
            echo "Not adding label."
          fi