name: Claude Code • auto-label issues

on:
  issues:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    name: Auto-label issues for Claude processing
    permissions:
      issues: write
    steps:
      # Checkout repo (required if you later read files)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install GitHub CLI and Claude CLI
      - name: Install GitHub & Claude CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          npm install -g @anthropic-ai/claude-code
    
      - name: Classify issue via Claude API
        env:
            ANTHROPIC_API_KEY: ${{ secrets.ANTHOPIC_API_KEY }}
            GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            
            ISSUE_TITLE: ${{ github.event.issue.title }}
            ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
            echo "Sending issue to Claude for classification..."
            echo "Issue #$ISSUE_NUMBER"
            echo "Title: $ISSUE_TITLE"
            echo "Body: $ISSUE_BODY"
            echo "GITHUB_TOKEN is set: ${GITHUB_TOKEN:+Yes}"
            echo "ANTHROPIC_API_KEY is set: ${ANTHROPIC_API_KEY:+Yes}"

            # Safely build JSON using jq to escape newlines/quotes
            DATA=$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" '{
                model: "claude-3-5-sonnet-20240620",
                max_tokens: 50,
                messages: [
                {
                    role: "user",
                    content: "Classify this GitHub issue into one of the following categories: broken_links, spelling_mistakes, grammatical_errors, formatting_issues, suggestions.\nTitle: \($title)\nBody: \($body)\nRespond ONLY with the category name."
                }
                ]
            }')

            RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
                -H "Content-Type: application/json" \
                -H "x-api-key: $ANTHROPIC_API_KEY" \
                -d "$DATA")

            CATEGORY=$(echo "$RESPONSE" | jq -r '.content[0].text' | tr -d '\n')
            echo "Claude classified the issue as: $CATEGORY"

            # Add label if category is detected
            if [[ -n "$CATEGORY" && "$CATEGORY" != "null" ]]; then
                gh issue edit $ISSUE_NUMBER --add-label "claude:queue"
            else
                echo "No valid category returned by Claude. Not adding label."
            fi
